dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: p1
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.11
- name: p2
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: p3
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: p4
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: ppppm
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
